name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Swift 6.0
        run: |
          SWIFT_VERSION="6.0.3"
          brew install swift
          sudo ln -sfn /opt/homebrew/opt/swift/Swift-6.0.xctoolchain /Applications/Xcode.app/Contents/Developer/Toolchains/Swift-6.0.xctoolchain
          echo 'export PATH="/opt/homebrew/opt/swift/bin:$PATH"' >> $HOME/.bash_profile
          echo 'export TOOLCHAINS=Swift-6.0.xctoolchain' >> $HOME/.bash_profile
          source $HOME/.bash_profile
          swift --version

      - name: Verify Swift version
        run: swift --version

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build Package
        run: swift build -v

      - name: Run Tests
        run: swift test --enable-code-coverage
